[package]
name = "hayatraQbot"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
tokio = "1.48.0"
traq-ws-bot = { version = "0.1.2", features = ["openapi"] }
